stages:

  feature_generating:
    cmd: python3 src/features/build_features.py data/raw/train.csv data/interim/train_featurized.csv
    deps:
    - data/raw
    outs:
    - data/interim:
        persist: true

  preprocess data:
    cmd: python3 src/features/preprocess_data.py data/interim/train_featurized.csv data/processed/x_train.csv data/processed/target.csv data/processed/enc.pkl
    deps:
    - data/interim
    outs:
    - data/processed:
        persist: true

  make dataset:
     cmd: python3 src/data/make_dataset.py data/processed/x_train.csv data/processed/target.csv data/train_val_datasets/x_train.csv data/train_val_datasets/target_train.csv data/train_val_datasets/x_val.csv data/train_val_datasets/target_val.csv
     deps:
     - data/processed
     outs:
     - data/train_val_datasets:
        persist: true

  train:
    cmd: python3 src/models/train_model.py  data/train_val_datasets/x_train.csv data/train_val_datasets/target_train.csv data/train_val_datasets/catboost
    deps:
    - data/train_val_datasets


  eval:
    cmd: python3 src/models/evaluate.py  data/train_val_datasets/x_val.csv data/train_val_datasets/target_val.csv data/train_val_datasets/catboost
    deps:
    - data/train_val_datasets


  # train:
  #   cmd: python3 src/models/train_model.py data/interim/train.pkl data/processed/target.pkl models/catboost data/validation_indexes/validx.csv

  #   deps:
  #   - data/interim
  #   - data/processed

  #   outs:

  #   - data/validation_indexes:
  #       persist: true

  #   - models/catboost:
  #       persist: true

  # eval:
  #   cmd: python3 src/models/evaluate.py data/interim/train.pkl data/processed/target.pkl models/catboost data/validation_indexes/validx.csv

  #   deps:
  #   - data/interim
  #   - data/processed
  #   - data/validation_indexes
  #   - models/catboost

  #   outs:
  #   - reports/figures:
  #       persist: true
